// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.ZippedImagingFilesScanner.GetDatasetNameViaPath(System.String)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.ThermoRawFileInfoScanner.StoreExtendedScanInfo(MSFileInfoScanner.DatasetStats.ExtendedStatsInfo,System.Collections.Generic.IReadOnlyCollection{System.Collections.Generic.KeyValuePair{System.String,System.String}})")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.AgilentGCDFolderInfoScanner.ProcessDataFile(System.String,MSFileInfoScanner.DatasetStats.DatasetFileInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.AgilentIonTrapDFolderInfoScanner.ExtractMethodLineDate(System.String,System.DateTime@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.AgilentIonTrapDFolderInfoScanner.ProcessDataFile(System.String,MSFileInfoScanner.DatasetStats.DatasetFileInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.AgilentTOFDFolderInfoScanner.ProcessContentsXMLFile(System.String,MSFileInfoScanner.DatasetStats.DatasetFileInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.AgilentTOFDFolderInfoScanner.ReadBinaryData(System.String,MSFileInfoScanner.DatasetStats.DatasetFileInfo,System.Double)")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.BrukerOneFolderInfoScanner.GetDatasetNameViaPath(System.String)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.BrukerOneFolderInfoScanner.ProcessDataFile(System.String,MSFileInfoScanner.DatasetStats.DatasetFileInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.BrukerXmassFolderInfoScanner.GetDatasetNameViaPath(System.String)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.BrukerXmassFolderInfoScanner.ReadDbInt(System.Data.IDataRecord,System.String)~System.Int32")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.FileIntegrityChecker.CheckZipFileIntegrity(System.String,System.Boolean,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.MSFileInfoDataCache.LoadCachedDirectoryIntegrityInfoResults")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.MSFileInfoDataCache.LoadCachedMSFileInfoResults")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.MSFileInfoDataCache.UpdateCachedDirectoryIntegrityInfo(MSFileInfoScanner.clsFileIntegrityChecker.udtDirectoryStatsType,System.Int32@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.MSFileInfoDataCache.UpdateCachedMSFileInfo(MSFileInfoScanner.DatasetStats.DatasetFileInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.MSFileInfoScanner.CheckForAbortProcessingFile")]
