// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsZippedImagingFilesScanner.GetDatasetNameViaPath(System.String)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsThermoRawFileInfoScanner.StoreExtendedScanInfo(MSFileInfoScanner.DatasetStats.ExtendedStatsInfo,System.Collections.Generic.IReadOnlyCollection{System.Collections.Generic.KeyValuePair{System.String,System.String}})")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsAgilentGCDFolderInfoScanner.ProcessDataFile(System.String,MSFileInfoScanner.DatasetStats.DatasetFileInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsAgilentIonTrapDFolderInfoScanner.ExtractMethodLineDate(System.String,System.DateTime@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsAgilentIonTrapDFolderInfoScanner.ProcessDataFile(System.String,MSFileInfoScanner.DatasetStats.DatasetFileInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsAgilentTOFDFolderInfoScanner.ProcessContentsXMLFile(System.String,MSFileInfoScanner.DatasetStats.DatasetFileInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsAgilentTOFDFolderInfoScanner.ReadBinaryData(System.String,MSFileInfoScanner.DatasetStats.DatasetFileInfo,System.Double)")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsBrukerOneFolderInfoScanner.GetDatasetNameViaPath(System.String)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsBrukerOneFolderInfoScanner.ProcessDataFile(System.String,MSFileInfoScanner.DatasetStats.DatasetFileInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsBrukerXmassFolderInfoScanner.GetDatasetNameViaPath(System.String)~System.String")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsBrukerXmassFolderInfoScanner.ReadDbInt(System.Data.IDataRecord,System.String)~System.Int32")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsFileIntegrityChecker.CheckZipFileIntegrity(System.String,System.Boolean,System.Boolean)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsMSFileInfoDataCache.LoadCachedDirectoryIntegrityInfoResults")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsMSFileInfoDataCache.LoadCachedMSFileInfoResults")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsMSFileInfoDataCache.UpdateCachedDirectoryIntegrityInfo(MSFileInfoScanner.clsFileIntegrityChecker.udtDirectoryStatsType,System.Int32@)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsMSFileInfoDataCache.UpdateCachedMSFileInfo(MSFileInfoScanner.DatasetStats.DatasetFileInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "RCS1075:Avoid empty catch clause that catches System.Exception.", Justification = "Ignore errors here", Scope = "member", Target = "~M:MSFileInfoScanner.clsMSFileInfoScanner.CheckForAbortProcessingFile")]
